[project]
name = "tt"
version = "0.1.0"
description = "Simple time tracker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
